Repository NCAR/ADF, pull requests merged in 2021-12, with the labels that each got.

#78 Add Github Issue templates
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: documentation, enhancement

#79 Make requested modifications to Github issue templates
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: documentation

#80 Per variable plotting options via YAML file
  .gitignore
  config_cam_baseline_example.yaml
  lib/adf_diag.py
  lib/adf_variable_defaults.yaml
  lib/plotting_functions.py
  scripts/plotting/global_latlon_map.py
  scripts/plotting/zonal_mean.py
Labels: enhancement, plotting, config files

#82 Fixed syntax bug in adf_diag.py
  lib/adf_diag.py
Labels: bug-fix
